### ISSUE TITLE
ulimit error

### ISSUE THREAD

**Issue by Soebb** [hmahdiany/dind#1]
I used your image but the container won't run because of ulimit error.
https://github.com/docker/cli/issues/4807#issue-2092216692
It seems it will be temporary fixed if the docker-ce==24.0.7-1 be installed.
Please update the image or make another, thanks.

**Comment by Soebb** [comment]
The better fix to adding :
```
RUN \
    echo "ulimits: $(ulimit -Sn):$(ulimit -Hn)"; \
    sed -i 's/ulimit -Hn/# ulimit -Hn/g' /etc/init.d/docker;
    #service docker start; \
    #rm -rf /var/cache/apt;
```

**Comment by hmahdiany** [comment]
Thanks @Soebb for using.
I've built and tested this Dockerfile on Ubuntu 20.04 with docker-ce=25.0.4 installed on it and the container runs without any problem, but I couldn't reproduce the problem to examine the exact bug and test the possible solution you've mentioned. Could you please give me more information about the environment on which you are using this Docker image?

**Comment by Soebb** [comment]
Not problem any more, it fixed as i said before.
I didn't use locally, i just used it to deploy to doprax.com
